# Generated by Django 5.2.1 on 2025-06-15 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('case', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('claim', models.TextField(blank=True, null=True)),
                ('claim_title', models.CharField(blank=True, max_length=255, null=True)),
                ('claim_text', models.TextField(blank=True, null=True)),
                ('attachment_file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('attachment_file_type', models.CharField(blank=True, max_length=100, null=True)),
                ('attachment_url', models.URLField(blank=True, null=True)),
                ('attachment_created_at', models.DateTimeField(blank=True, null=True)),
                ('is_judgement_note', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='case.case')),
            ],
        ),
    ]
