# Generated by Django 5.2.1 on 2025-06-15 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('case', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('عالية', 'عالية'), ('متوسطة', 'متوسطة'), ('منخفضة', 'منخفضة')], max_length=20, null=True)),
                ('status', models.CharField(choices=[('جديدة', 'جديدة'), ('قيد التنفيذ', 'قيد التنفيذ'), ('مكتملة', 'مكتملة'), ('ملغاة', 'ملغاة')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='case.case')),
            ],
        ),
    ]
