# Generated by Django 5.2.1 on 2025-06-11 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('agency_number', models.CharField(max_length=100, unique=True)),
                ('agency_history', models.TextField(blank=True, null=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('comments', models.TextField(blank=True, null=True)),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('national_id_or_residence_number', models.CharField(blank=True, max_length=50, null=True)),
                ('commercial_register', models.CharField(blank=True, max_length=100, null=True)),
                ('nature_of_activity', models.CharField(blank=True, max_length=255, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('national_address', models.TextField(blank=True, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('iban_number', models.CharField(blank=True, max_length=34, null=True)),
                ('additional_mobile_number', models.CharField(blank=True, max_length=20, null=True)),
                ('current_profession', models.CharField(blank=True, max_length=100, null=True)),
                ('employer', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
