# Generated by Django 5.2.1 on 2025-06-12 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='agency_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
