# Generated by Django 5.2.1 on 2025-06-13 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_client_agency_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='national_id_or_residence_number',
            new_name='national_id',
        ),
        migrations.AddField(
            model_name='client',
            name='gender',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='agency_number',
            field=models.CharField(max_length=100),
        ),
    ]
