# Generated by Django 5.2.1 on 2025-06-14 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_rename_national_id_or_residence_number_client_national_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='amount_due',
            new_name='amount_paid',
        ),
        migrations.AddField(
            model_name='client',
            name='total_due',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
