# Generated by Django 5.2.1 on 2025-06-15 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0007_alter_client_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_name', models.CharField(blank=True, max_length=255, null=True)),
                ('closed', models.BooleanField(default=False)),
                ('closing_info', models.TextField(blank=True, null=True)),
                ('closing_info_status', models.CharField(blank=True, max_length=50, null=True)),
                ('closing_info_percentage', models.CharField(blank=True, max_length=10, null=True)),
                ('my_case_note', models.TextField(blank=True, null=True)),
                ('my_case_note_updated', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='client.client')),
            ],
        ),
    ]
