# Generated by Django 5.2.1 on 2025-10-28 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_is_active_user_parent_user_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='terms_accepted',
            field=models.BooleanField(default=False, help_text='Indicates whether the user has accepted the terms and conditions'),
        ),
    ]
