# Generated by Django 5.2.1 on 2026-01-10 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_terms_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deletion_requested_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when user requested account deletion. Account will be deleted after 30 days if no login occurs.', null=True),
        ),
    ]
